import { launch, shot, log, api, BASE } from './lib.mjs';
const { browser, page } = await launch('1440x900');
log('=== S11 world settings: plants at agent starts off, initial fruit 0 (created from the UI)');
await page.goto(`${BASE}/#/new`); await page.waitForTimeout(2000);
await page.getByLabel('Run name').fill('retest world fields off');
const cb = page.getByLabel(/plants at agent starts/i).first();
await cb.uncheck();
const fr = page.getByLabel(/initial fruit per plant/i).first();
await fr.fill('0'); await fr.press('Tab');
await page.getByRole('heading', { name: /^World$/ }).evaluate((e) => { e.scrollIntoView({ block: 'start' }); window.scrollBy(0, -70); });
await shot(page, 'k01-world-fields-off');
const bar = page.getByRole('region', { name: 'Setup actions' }).first();
await bar.getByRole('button', { name: 'Create and open' }).click();
await page.waitForURL(/#\/run\//, { timeout: 20000 }); await page.waitForTimeout(2500);
const runId = decodeURIComponent(page.url().split('#/run/')[1].split('?')[0]);
const init = (await api(`/runs/${runId}/turns/r00000_init`)).body;
const starts = new Set(Object.values(init.entities.agents).map((a) => `${a.position.x},${a.position.y}`));
const plantsAtStarts = Object.values(init.entities.plants).filter((p) => starts.has(`${p.position.x},${p.position.y}`)).map((p) => p.id);
log('run', runId, 'plants', Object.keys(init.entities.plants).length, 'fruits', Object.keys(init.entities.fruits).length, 'plants on agent start cells', plantsAtStarts);
const settings = (await api(`/runs/${runId}/turns/r00000_init`)).body;
await page.getByRole('button', { name: 'Back to sessions' }).click(); await page.waitForTimeout(1000);
await browser.close();
