import { launch, shot, evidence, log, loadState, saveState, api, status, sleep, statusText, BASE } from './lib.mjs';
const st = loadState(); const runId = st.mainRun;
const { browser, page } = await launch('1440x900');
log(`=== S7 continuation + resume on ${runId}`);
await page.goto(`${BASE}/#/run/${runId}`); await page.waitForTimeout(3000);
const tl = page.getByRole('region', { name: 'History timeline' });
await tl.getByRole('button', { name: /Previous round/ }).click(); await page.waitForTimeout(1500);
const sel = tl.locator('select');
const opts = await sel.locator('option').evaluateAll((os) => os.map((o) => o.value));
const from = opts.find((v) => /_t04_/.test(v)) || opts[2];
await sel.selectOption(from); await page.waitForTimeout(1800);
await page.getByRole('tab', { name: /God mode/ }).click(); await page.waitForTimeout(1200);
const btn = page.getByRole('button', { name: /Create continuation from turn/ });
log('continuation button:', await btn.innerText());
await btn.scrollIntoViewIfNeeded(); await shot(page, 'g01-continuation-button');
await btn.click();
await page.waitForURL((u) => !u.toString().includes(runId), { timeout: 20000 }).catch((e) => log('did not navigate', String(e).slice(0, 100)));
await page.waitForTimeout(3500);
const newId = decodeURIComponent(page.url().split('#/run/')[1]?.split('?')[0] || '');
log('landed on', newId);
log('timeline:', (await page.getByRole('region', { name: 'History timeline' }).innerText()).replace(/\n/g, ' / ').slice(0, 400));
log('status:', await statusText(page));
const sum = (await api(`/runs/${newId}`)).body;
log('api summary parent', JSON.stringify(sum.parent), 'name', sum.name, 'current', sum.current_turn_id);
await page.evaluate(() => window.scrollTo(0, 0));
await evidence(page, '16-continuation');
st.contRun = newId; st.contFrom = from; saveState(st);
// ---- resume: back to sessions, resume list, open the main run
await page.getByRole('button', { name: 'Back to sessions' }).click(); await page.waitForTimeout(1500);
log('after back url', page.url(), 'status of cont run (expect closed/409):', (await api(`/runs/${newId}/status`)).status);
await page.getByRole('button', { name: /Resume session/ }).click(); await page.waitForTimeout(2500);
await evidence(page, '18-resume-session');
const listTxt = await page.locator('body').innerText();
log('resume list head:', listTxt.slice(0, 900).replace(/\n+/g, ' | '));
const opener = page.getByRole('button', { name: new RegExp(`Open ${st.mainName}$`) }).first();
log('open button for main run', await opener.count());
await opener.click();
await page.waitForURL(/#\/run\//, { timeout: 10000 }).catch(() => {});
await page.waitForTimeout(3000);
const s = await status(runId);
log('resumed', page.url(), 'badge', await page.locator('.state-badge').first().innerText(), 'api', s.state, s.current_turn_id);
await shot(page, 'g02-resumed-main');
await browser.close();
