import { launch, shot, evidence, log, loadState, saveState, api, status, sleep, waitIdle, statusText, BASE } from './lib.mjs';
const st = loadState();
const d = (await api('/defaults?agent_count=8')).body;
d.name = 'retest error run (503 x3)'; d.play_delay_seconds = 0;
for (const c of d.agents) c.fake_options = { fail: { status: 'error', http_status: 503, rounds: [1], failing_attempts: 3 } };
const cr = await api('/runs', { method: 'POST', body: d });
const runId = cr.body.run_id; st.errRun = runId; saveState(st);
log(`=== S9 error state + recover + re-run on ${runId}`);
const { browser, page } = await launch('1440x900');
await page.goto(`${BASE}/#/run/${runId}`); await page.waitForTimeout(3000);
await page.getByRole('button', { name: 'Run turn', exact: true }).click();
const seq = []; const t0 = Date.now();
while (Date.now() - t0 < 30000) { const b = (await page.locator('.state-badge').first().innerText()).trim(); if (seq[seq.length - 1] !== b) seq.push(b); if (/error/i.test(b)) break; await sleep(150); }
await page.waitForTimeout(2000);
log('badge sequence', seq);
log('status bar in error:', await statusText(page));
const failed = await page.locator('.failed-turn').innerText().catch(() => '(no failed-turn panel)');
log('failed-turn panel:', failed.replace(/\n/g, ' | '));
const pend = await page.locator('.log-pending-note').allInnerTexts();
log('pending notes:', pend);
const lines = await page.locator('.log-line').evaluateAll((ls) => ls.map((l) => l.innerText.replace(/\n/g, ' ~ ')));
for (const l of lines) log('   ', l.slice(0, 320));
for (const n of ['Run turn', 'Play', 'Pause', 'Step round']) log(`in error: ${n} disabled=${await page.getByRole('button', { name: n, exact: true }).isDisabled()}`);
await evidence(page, '17-error-state');
// Recover
await page.getByRole('button', { name: /Recover/ }).click(); await page.waitForTimeout(2500);
let s = await status(runId);
log('after recover', s.state, s.current_turn_id, 'badge', await page.locator('.state-badge').first().innerText());
log('status after recover:', await statusText(page));
const linesR = await page.locator('.log-line').evaluateAll((ls) => ls.map((l) => `${l.className.replace('log-line', '').trim()} :: ${l.innerText.replace(/\n/g, ' ~ ')}`));
for (const l of linesR) log('   R', l.slice(0, 300));
await shot(page, 'i01-after-recover');
// Re-run (the fake fails 3 attempts of call _01, so call _02 succeeds)
await page.getByRole('button', { name: 'Run turn', exact: true }).click(); await sleep(800);
s = await waitIdle(runId); await page.waitForTimeout(2500);
log('after re-run', s.state, s.current_turn_id);
const linesA = await page.locator('.log-line').evaluateAll((ls) => ls.map((l) => `${l.className.replace('log-line', '').trim()} :: ${l.innerText.replace(/\n/g, ' ~ ')}`));
for (const l of linesA) log('   A', l.slice(0, 300));
const decor = await page.locator('.log-line.cat-discarded').evaluateAll((ls) => ls.map((l) => getComputedStyle(l.querySelector('.log-summary')).textDecorationLine));
log('discarded lines text-decoration:', decor);
await page.locator('section.activity-log').screenshot({ path: new URL('./shots/i02-log-after-rerun.png', import.meta.url).pathname });
await shot(page, 'i03-after-rerun');
const tv = (await api(`/runs/${runId}/turns/${s.current_turn_id}`)).body;
log('saved turn event seqs', tv.turn.event_seq_start, '-', tv.turn.event_seq_end, 'kinds', tv.events.map((e) => `${e.seq}:${e.kind}`).join(' '));
log('model calls in the saved turn:', tv.model_calls.map((c) => `${c.call_id}:${c.status}:${c.provider_cost_usd}`));
log('status usage', JSON.stringify(s.real_usage));
await page.getByRole('tab', { name: /Turn record/ }).click(); await page.waitForTimeout(1500);
await shot(page, 'i04-turn-record-after-rerun');
await browser.close();
await api(`/runs/${runId}/close`, { method: 'POST' });
