import { launch, shot, log, loadState, saveState, api, sleep, BASE } from './lib.mjs';
const st = loadState(); const runId = st.runId;
const { browser, page } = await launch();
log('=== STEP 4: timeline on', runId);
await page.goto(`${BASE}/#/run/${runId}`);
await page.waitForTimeout(2000);
const tl = page.getByRole('region', { name: 'History timeline' });
const mode = async () => (await tl.locator('.timeline-mode').innerText()).replace(/\n/g,' ');
const logCount = async () => (await page.getByRole('region', { name: 'Live activity log' }).locator('.activity-log-count, header').first().innerText().catch(()=> '')).replace(/\n/g,' ');
const logHeader = async () => (await page.getByRole('region', { name: 'Live activity log' }).innerText()).split('\n').slice(0,2).join(' ');
const tabLabel = async () => (await page.getByRole('tab').allInnerTexts().catch(()=>[])).join(' | ');
log('mode live:', await mode());
await tl.getByRole('button', { name: /Previous round/ }).click();
await page.waitForTimeout(1500);
log('after prev round:', await mode());
log('turn select value:', await tl.locator('select').inputValue());
log('status badge still:', await page.locator('.state-badge').first().innerText());
const tabs = await page.locator('[role=tab], .tabs button, .tab').allInnerTexts().catch(()=>[]);
log('tabs', tabs);
await shot(page, '17-history-previous-round');
await tl.getByRole('button', { name: /Previous round/ }).click();
await page.waitForTimeout(1200);
log('after 2x prev round:', await mode());
await tl.getByRole('button', { name: /Next round/ }).click();
await page.waitForTimeout(1200);
log('after next round:', await mode());
// turn select: choose the 3rd option in the dropdown
const sel = tl.locator('select');
const opts = await sel.locator('option').evaluateAll(os => os.map(o => ({ v: o.value, t: o.textContent })));
log('turn options', opts.map(o => o.t));
await sel.selectOption(opts[2].v);
await page.waitForTimeout(1500);
log('after select turn', opts[2].v, ':', await mode());
await shot(page, '18-history-turn-selected');
await tl.getByRole('button', { name: /Next turn/ }).click();
await page.waitForTimeout(1000);
log('after next turn:', await mode());
await tl.getByRole('button', { name: /Previous turn/ }).click();
await page.waitForTimeout(1000);
log('after prev turn:', await mode());
// while in history, advance the live run: click Run turn in the UI (if enabled)
const logBefore = await logHeader();
const rt = page.getByRole('button', { name: 'Run turn', exact: true });
log('Run turn enabled in history?', !(await rt.isDisabled()));
if (!(await rt.isDisabled())) await rt.click(); else await api(`/runs/${runId}/commands`, { method: 'POST', body: { command: 'run_turn' } });
await page.waitForTimeout(2500);
const logAfter = await logHeader();
log('log header before/after live turn while in history:', logBefore, '=>', logAfter);
log('mode after live turn:', await mode());
log('status bar:', (await page.getByRole('region', { name: 'Run status' }).innerText()).replace(/\n+/g,' | ').slice(0,300));
await shot(page, '19-history-while-live-advances');
// map heading / checkpoint indicator near map?
const mapHead = await page.locator('.map-view, [aria-label*="map" i]').first().innerText().catch(()=> '');
log('map area header text:', mapHead.split('\n').slice(0,4).join(' / '));
await tl.getByRole('button', { name: 'Return to live' }).click();
await page.waitForTimeout(1500);
log('after return to live:', await mode());
await shot(page, '20-returned-to-live');
await browser.close();
