import { launch, shot, log, loadState, saveState, api, sleep, BASE } from './lib.mjs';
const st = loadState(); const runId = st.runId;
const VP = process.env.VP || '1440x900'; const P = process.env.PREFIX || '';
const { browser, page } = await launch(VP);
log(`=== STEP 5: map (${VP}) on`, runId);
await page.goto(`${BASE}/#/run/${runId}`);
await page.waitForTimeout(2500);
const s = (await api(`/runs/${runId}/state`)).body;
const occ = Object.entries(s.map.occupants).sort((a,b)=>b[1].length-a[1].length);
const [coord, ids] = process.env.COORD ? [process.env.COORD, s.map.occupants[process.env.COORD]] : occ[0];
log('crowded coordinate', coord, ids, 'turn', s.turn.turn_id);
const [cx, cy] = coord.split(',');
// center there with Go to
await page.getByLabel('Go to x').fill(cx); await page.getByLabel('Go to y').fill(cy);
await page.getByRole('button', { name: 'Go', exact: true }).click();
await page.waitForTimeout(600);
const cell = page.locator(`rect[data-coord="${coord}"]`);
log('cell count', await cell.count());
await cell.hover();
await page.waitForTimeout(700);
const tip = page.getByRole('tooltip');
log('tooltip visible', await tip.isVisible().catch(()=>false));
const tipText = await tip.innerText().catch(()=> '');
log('tooltip text:', tipText.replace(/\n/g,' / '));
log('tooltip lists all occupants', ids.every(i => tipText.includes(i)));
await shot(page, `${P}21-map-hover-crowded`);
await cell.click();
await page.waitForTimeout(1200);
const occPanel = page.locator('.insp-occupants');
const occText = await occPanel.innerText();
log('occupant panel:', occText.replace(/\n/g,' / ').slice(0,600));
log('occupants all listed', ids.every(i => occText.includes(i)));
const scrollInfo = await page.locator('.insp-occupants-scroll').evaluate(e => ({ sh: e.scrollHeight, ch: e.clientHeight, overflowY: getComputedStyle(e).overflowY, maxH: getComputedStyle(e).maxHeight }));
log('occupant scroll box', scrollInfo);
await shot(page, `${P}22-map-click-crowded`);
const rows = page.locator('.insp-occupant-row');
const n = await rows.count();
log('occupant rows', n, await rows.evaluateAll(rs => rs.map(r => r.getAttribute('aria-label'))));
const insp = page.locator('.insp-inspector');
for (let i = 0; i < Math.min(n, 12); i++) {
  await rows.nth(i).click();
  await page.waitForTimeout(1500);
  const head = (await insp.locator('.insp-panel-title').first().innerText()).replace(/\n/g,' ');
  const txt = await insp.innerText();
  const secs = await insp.locator('.insp-section-title, h3, h4, summary').allInnerTexts().catch(()=>[]);
  log(`occupant ${i}: ${head} | sections: ${secs.join(' ; ').slice(0,500)}`);
  if (i < 3) await insp.screenshot({ path: new URL(`./shots/${P}23-inspector-occupant-${i}.png`, import.meta.url).pathname });
}
await browser.close();
