import { launch, shot, log, loadState, saveState, api, BASE, sleep } from './lib.mjs';
const st = loadState(); const runId = st.runId;
const { browser, page } = await launch();
log('=== STEP 7b: place + agent context + apply on', runId);
await page.goto(`${BASE}/#/run/${runId}`); await page.waitForTimeout(2500);
const statusStaged = async () => (await page.getByRole('region', { name: 'Run status' }).innerText()).replace(/\n/g,' ').match(/STAGED EDITS\s+(\d+)/i)?.[1];
log('status bar staged edits on load:', await statusStaged(), 'api staged', (await api(`/runs/${runId}/interventions`)).body.staged.length);
await page.getByRole('tab', { name: /God mode/ }).click(); await page.waitForTimeout(1000);
await page.getByRole('tab', { name: 'Place entity', exact: true }).click(); await page.waitForTimeout(300);
await page.locator('#gm-pe-kind').selectOption('fruit');
await page.locator('#gm-pe-pos-x').fill('1'); await page.locator('#gm-pe-pos-y').fill('0');
await page.locator('#gm-pe-compute').fill('30');
await page.getByRole('button', { name: /Stage placement/ }).click(); await page.waitForTimeout(1200);
log('after place:', (await page.locator('.ok-line, .insp-ok, [role=alert]').allInnerTexts()).slice(-1));
await page.getByRole('tab', { name: 'Context settings', exact: true }).click(); await page.waitForTimeout(300);
await page.locator('#gm-cs-scope').selectOption('a03'); await page.waitForTimeout(300);
const row = page.locator('tr').filter({ hasText: 'Retrieved memory limit' }).last();
await row.getByRole('checkbox').check(); await page.waitForTimeout(200);
await row.getByLabel('Retrieved memory limit').fill('3');
await page.getByRole('button', { name: /Stage override for a03/ }).click(); await page.waitForTimeout(1200);
log('after agent ctx:', (await page.locator('.ok-line, .insp-ok, [role=alert]').allInnerTexts()).slice(-1));
await sleep(2500);
log('status bar staged edits after 2.5s:', await statusStaged(), 'api staged', (await api(`/runs/${runId}/interventions`)).body.staged.length, 'tab:', await page.getByRole('tab', { name: /God mode/ }).innerText());
const list = page.getByText(/Staged edits \(\d+\)/).first();
await list.scrollIntoViewIfNeeded();
await shot(page, '41-god-all-staged');
// apply with Run turn
const before = (await api(`/runs/${runId}/status`)).body.current_turn_id;
await page.getByRole('button', { name: 'Run turn', exact: true }).click();
await sleep(3000);
const after = (await api(`/runs/${runId}/status`)).body;
log('run turn applied:', before, '->', after.current_turn_id, 'staged now', (await api(`/runs/${runId}/interventions`)).body.staged.length);
await page.evaluate(() => window.scrollTo(0,0));
// uncheck hide routine / show operator events in log
const logTxt = await page.getByRole('region', { name: 'Live activity log' }).innerText();
const opLines = logTxt.split('\n').filter(l => /operator|intervention|voice/i.test(l));
log('operator lines in log:', opLines.slice(-14));
await shot(page, '42-log-after-interventions-applied');
await page.locator('.activity-log').screenshot({ path: new URL('./shots/43-activity-log-operator-lines.png', import.meta.url).pathname });
// verify via API
const tv = (await api(`/runs/${runId}/turns/${after.current_turn_id}`)).body;
log('turn interventions recorded:', (tv.turn.interventions||[]).map(r => `${r.intervention?.id||r.id}:${r.intervention?.type||r.type}:ok=${r.ok}`));
const fruits = Object.values(tv.entities.fruits);
log('fruits now:', fruits.map(f => `${f.id}@${f.position.x},${f.position.y} c=${f.available_compute}`));
log('a03 compute', tv.entities.agents.a03.stats.compute, 'context', JSON.stringify(tv.settings.context.recent_history_length), 'a03 override', JSON.stringify(tv.settings.context_overrides.a03));
const k2 = (await api(`/runs/${runId}/agents/a02/knowledge`)).body;
const k5 = (await api(`/runs/${runId}/agents/a05/knowledge`)).body;
const vv = r => (r.records||[]).filter(x => x.kind === 'operator_voice').map(x => x.text);
log('a02 voices', vv(k2), 'a05 voices', vv(k5));
st.placedFruit = fruits.find(f => f.position.x===1 && f.position.y===0)?.id; saveState(st);
await browser.close();
