import { launch, shot, log, loadState, saveState, api, BASE, sleep } from './lib.mjs';
const st = loadState(); const runId = st.runId;
const { browser, page } = await launch();
log('=== STEP 7d: continuation from history on', runId);
await page.goto(`${BASE}/#/run/${runId}`); await page.waitForTimeout(2500);
const tl = page.getByRole('region', { name: 'History timeline' });
await tl.getByRole('button', { name: /Previous round/ }).click(); await page.waitForTimeout(1200);
await tl.getByRole('button', { name: /Previous round/ }).click(); await page.waitForTimeout(1200);
const sel = tl.locator('select');
const opts = await sel.locator('option').evaluateAll(os => os.map(o => o.value));
const from = opts.find(v => /_t03_/.test(v)) || opts[2];
await sel.selectOption(from); await page.waitForTimeout(1500);
log('viewing', await tl.locator('.timeline-mode').innerText());
await page.getByRole('tab', { name: /God mode/ }).click(); await page.waitForTimeout(1200);
await shot(page, '48-godmode-in-history');
const godTop = (await page.locator('#panel-god, [role=tabpanel]:not([hidden])').first().innerText()).split('\n').slice(0, 6).join(' / ');
log('god mode panel top in history:', godTop);
const btn = page.getByRole('button', { name: /Create continuation from turn/ });
log('continuation button:', await btn.innerText());
await btn.scrollIntoViewIfNeeded(); await shot(page, '49-continuation-button');
await btn.click();
await page.waitForURL(u => !u.toString().includes(runId), { timeout: 15000 }).catch(e => log('did not navigate', String(e).slice(0,100)));
await page.waitForTimeout(3000);
const newId = decodeURIComponent(page.url().split('#/run/')[1]?.split('?')[0] || '');
log('landed on', page.url(), 'new run', newId);
await shot(page, '50-continuation-landed');
const hdr = (await page.locator('.page-header, header, h1').first().innerText()).replace(/\n/g,' ');
log('header', hdr);
log('timeline', (await page.getByRole('region', { name: 'History timeline' }).innerText()).replace(/\n/g,' / '));
log('status', (await page.getByRole('region', { name: 'Run status' }).innerText()).replace(/\n+/g,' | ').slice(0, 300));
const sum = (await api(`/runs/${newId}`)).body;
log('api summary parent', JSON.stringify(sum.parent), 'name', sum.name, 'last turn', sum.last_turn_id || sum.current_turn_id);
st.contRunId = newId; st.contFrom = from; saveState(st);
// parent link button
const parentBtn = page.getByRole('button', { name: /Open parent run at that turn|Parent run/ }).first();
log('parent button present', await parentBtn.count());
await parentBtn.click(); await page.waitForTimeout(3000);
log('after parent click url', page.url());
log('timeline after parent click', (await page.getByRole('region', { name: 'History timeline' }).innerText()).replace(/\n/g,' / ').slice(0,300));
await shot(page, '51-parent-run-opened-at-turn');
await browser.close();
