import { launch, shot, log, loadState, saveState, api, BASE, sleep } from './lib.mjs';
const st = loadState(); const runId = st.runId;
const { browser, page } = await launch();
log('=== STEP 8: leave + resume', runId);
await page.goto(`${BASE}/#/run/${runId}`); await page.waitForTimeout(2500);
const lastBefore = (await api(`/runs/${runId}/status`)).body.current_turn_id;
log('live turn before leaving', lastBefore);
await page.getByRole('button', { name: 'Back to sessions' }).click(); await page.waitForTimeout(1500);
log('after Back to sessions url', page.url());
await shot(page, '52-after-back-to-sessions');
const st2 = await api(`/runs/${runId}/status`);
log('status after leaving (expect run_not_open 409):', st2.status, JSON.stringify(st2.body).slice(0,120));
if (!page.url().endsWith('#/')) { await page.goto(`${BASE}/#/`); await page.waitForTimeout(800); }
await page.getByRole('button', { name: /Resume session/ }).click(); await page.waitForTimeout(2000);
await shot(page, '53-resume-list');
const listTxt = await page.locator('body').innerText();
console.log(listTxt.slice(0, 1500));
const row = page.getByRole('row', { name: new RegExp(st.runName) }).first();
const rowCount = await row.count();
log('row for run found', rowCount);
let opener = rowCount ? row.getByRole('button', { name: /Open|Resume/ }).first() : page.getByRole('button', { name: new RegExp(st.runName) }).first();
if (!(await opener.count())) opener = page.getByText(st.runName, { exact: true }).first();
await opener.click();
await page.waitForURL(/#\/run\//, { timeout: 10000 }).catch(()=>{});
await page.waitForTimeout(2500);
log('opened url', page.url());
const badge = await page.locator('.state-badge').first().innerText();
const s = (await api(`/runs/${runId}/status`)).body;
log('resumed badge', badge, 'api state', s.state, 'turn', s.current_turn_id, 'matches last saved:', s.current_turn_id === lastBefore);
log('timeline', (await page.getByRole('region', { name: 'History timeline' }).innerText()).split('\n').slice(0,2).join(' '));
await shot(page, '54-resumed-run');
await browser.close();
